apiVersion: v1
kind: Service
metadata:
  name: grpc-client-service
spec:
  selector:
    app: grpc-client
  ports:
    - protocol: "TCP"
      port: 5051 # service port
      targetPort: 50051
  type: ClusterIP # 외부와 통신은 필요함. 그러나 외부에서는 접근할 수 없음. NAT를 통해 접근 가능.

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
spec:
  selector:
    matchLabels: # template labels must match this spec. 이 deployment가 관리하는 pod의 label.
      app: grpc-client
  replicas: 3
  template:
    metadata:
      labels: # template labels
        app: grpc-client
    spec:
      containers:
        - name: grpc-client          
          image: # Add your image here
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: grpc-client-config
          ports:
            - containerPort: 50051