# k8s-grpc-internal.yaml
apiVersion: v1
kind: Service
metadata:
  name: grpc-internal-service
spec:
  selector:
    app: grpc-internal
  ports:
    - protocol: "TCP"
      port: 5053
      targetPort: 50053
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-internal
spec:
  selector:
    matchLabels:
      app: grpc-internal # internal label을 가진 pod 관리
  replicas: 3
  template: # pod 템플릿 설정
    metadata:
      labels:
        app: grpc-internal
    spec:
      containers:
      - name: grpc-internal
        image: grpc-internal # 이미지 이름은 실제 레지스트리에 맞게 수정 필요
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: grpc-internal-config
        ports:
          - containerPort: 50053
